### ISSUE TITLE
Trying to send an identify failure

### ISSUE THREAD

**Issue by gonzalosperalta** [agorapulse/grails-segment#4]
Hello, I'm trying to use this plugin to send an identify, but when I execute the code:

def mapToSend = [
                         email         : user.email,
                         fname     : user.firstname,
                         lname      : user.lastname]
                         ]

segmentioService.identify( '123456', mapToSend)

This message is shown:

GRAILS-7799: Subtype 'grails.plugin.segmentio.SegmentioService$$EnhancerByCGLIB$$a7fdc2e7' of reloadable type grails.plugin.segmentio.SegmentioService is not reloadable: may not see changes reloaded in this hierarchy (please comment on that jira)

I'm using Grails 2.1.0

My buildConfig:

dependency {
...
build 'org.apache.httpcomponents:httpcore:4.3.2'
        build 'org.apache.httpcomponents:httpclient:4.3.5'
        runtime 'org.apache.httpcomponents:httpcore:4.3.2'
        runtime 'org.apache.httpcomponents:httpclient:4.3.5'
}

plugins {
...
compile ":segmentio:1.0.7.1"
}

My Config.groovy

grails.plugin.segmentio.apiKey = 'this is the api key' // Write key
grails.plugin.segmentio.serverApiKey = 'this is the api key'
grails.plugin.segmentio.enabled = true
// Queue size limit
grails.plugin.segmentio.maxQueueSize = 10000
// The amount of milliseconds that passes before a request is marked as timed out
grails.plugin.segmentio.timeout = 10000
// How many times to retry the request.
grails.plugin.segmentio.retries = 2
// Backoff in milliseconds between retries.
grails.plugin.segmentio.backoff = 1000

Any idea?

**Comment by benorama** [comment]
I vaguely remember having similar issues.
It's probably linked to dependencies / libs clash.
Have you tried upgraded to latest Grails version 2.4 or 2.5?
